<a href="https://colab.research.google.com/github/sathyabamasrsep13/A1-job-market-skill-analyzer/blob/main/Numpy_Pandas_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Analytics (DA)

#    Module -5

# Python DA Assignment 1—Numpy and Pandas

# Assignment Task Overview

This assignment focuses on performing data analysis using NumPy and Pandas.

The objective is to:

● Work with NumPy arrays for numerical computations

● Use Pandas Series and DataFrame for data manipulation and analysis

● Apply indexing, slicing, filtering, and aggregation techniques

● Understand real-world data handling through temperature and transaction datasets

You will analyze temperature data using NumPy and perform structured data analysis using Pandas.

# Tasks:
# Numpy Array Operations:

# Scenario:
 You are given a list of daily average temperatures (in degrees Celsius) recorded over two
weeks.
 Your task is to use NumPy to analyze this data.

1. Create a 1D NumPy Array:

Create a 1D NumPy array named temperatures_w1 for Week 1 with the following
values:

[22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9]

In [1]:
import numpy as np

temperatures_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])

print(temperatures_w1)

[22.5 25.3 20.8 23.4 26.1 24.8 21.9]


# 2. Inspection and Properties:

● Inspect the shape, data type, and the number of elements in the array. Inspect
the shape of the temperatures_w1 array.

In [2]:
print("Shape:", temperatures_w1.shape)
print("Data Type:", temperatures_w1.dtype)
print("Number of Elements:", temperatures_w1.size)

Shape: (7,)
Data Type: float64
Number of Elements: 7


# 3. Array Operations:

● Convert the temperatures_w1 from Celsius to Fahrenheit using the formula:
Fahrenheit = (Celsius * 9/5) + 32

● Find the maximum, minimum, and mean temperatures for the week.

In [3]:
#Celsius → Fahrenheit

#Formula:

#Fahrenheit = (Celsius × 9/5) + 32

fahrenheit = (temperatures_w1 * 9/5) + 32

print("Fahrenheit:", fahrenheit)

Fahrenheit: [72.5  77.54 69.44 74.12 78.98 76.64 71.42]


In [4]:
# Maximum,Minimum,Mean

print("Maximum:", np.max(temperatures_w1))

print("Minimum:", np.min(temperatures_w1))

print("Mean:", np.mean(temperatures_w1))

Maximum: 26.1
Minimum: 20.8
Mean: 23.542857142857144


# 4. Array Slicing and Indexing:

● Extract the temperatures for the first three days of the week.

● Extract the temperatures for the weekend (last two days).

● Extract the temperatures for the middle three days of the week.

In [5]:
# First three days of the week

print(temperatures_w1[:3])

[22.5 25.3 20.8]


In [6]:
#  Weekend (last two days)

print(temperatures_w1[-2:])

[24.8 21.9]


In [7]:
# Middle three days of the week

print(temperatures_w1[2:5])

[20.8 23.4 26.1]


# 5. Create a 2D Array:

Create a 2D NumPy array named temperatures where each row represents
temperatures for a different week:

★ Row 1: [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9] (Week 1)

★ Row 2: [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1] (Week 2)

In [8]:
temperatures = np.array([
    [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],
    [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]
])

print(temperatures)

[[22.5 25.3 20.8 23.4 26.1 24.8 21.9]
 [19.2 22.5 21.3 24.  23.5 22.8 20.1]]


# 6. Inspect and Slice the 2D Array:

● Inspect and print the shape, data type, and total number of elements in the
temperatures array.

● Extract the temperatures for each week and the weekends (last two days) for
both weeks.

In [10]:
print("Shape:", temperatures.shape)

print("Data Type:", temperatures.dtype)

print("Total Number of Elements:", temperatures.size)

Shape: (2, 7)
Data Type: float64
Total Number of Elements: 14


# Pandas Series:

# 1. Creating Pandas Series:

● Create a Pandas Series named marks with the following data:

➢ Marks: 95, 92, 89, 85, 80

➢ Custom Indices: 'Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5'

In [11]:
import pandas as pd

marks = pd.Series(
    [95, 92, 89, 85, 80],
    index=['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5']
)

print(marks)

Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
dtype: int64


# 2. Indexing and Slicing:

● Use the integer index position to access the mark of the 1st rank student.

● Use the loc accessor to retrieve the marks of the top 3 ranks by specifying their index
labels.

● Use the iloc accessor to retrieve the mark of the 3rd-ranked student.

● Apply a boolean mask to filter the Series and retrieve the ranks where the marks are
greater than 90.

In [13]:
# Mark of the 1st rank student

print(marks.iloc[0])

95


In [14]:
# Retrieve the marks of the top 3 ranks by specifying their index labels(Use loc)

print(marks.loc[['Rank1', 'Rank2', 'Rank3']])

Rank1    95
Rank2    92
Rank3    89
dtype: int64


In [15]:
# Retrieve the mark of the 3rd-ranked student

print(marks.iloc[2])

89


In [16]:
# Retrieve the ranks where the marks are greater than 90(Boolean masking)

result = marks[marks > 90]

print(result)

Rank1    95
Rank2    92
dtype: int64


# 3. Manipulating Series:

● Modify the mark of the student with the 1st rank to 100.

● Remove the entry corresponding to the last rank from the Series.

● Compute the CGPA by dividing each mark in the Series by 10.

In [17]:
# Modify the mark of the student with the 1st rank to 100

marks.loc['Rank1'] = 100

print(marks)

Rank1    100
Rank2     92
Rank3     89
Rank4     85
Rank5     80
dtype: int64


In [18]:
# Remove the entry corresponding to the last rank from the Series.

marks = marks.drop('Rank5')

print(marks)

Rank1    100
Rank2     92
Rank3     89
Rank4     85
dtype: int64


In [19]:
# Compute the CGPA by dividing each mark in the Series by 10.

cgpa = marks / 10

print(cgpa)

Rank1    10.0
Rank2     9.2
Rank3     8.9
Rank4     8.5
dtype: float64


# Pandas DataFrame:

# 1. Creating Pandas DataFrame:

● Create a Pandas DataFrame named transactions with the following data:

 ➢TransactionID: 101, 102, 103, 104, 105, 106, 107, 108, 109, 110

➢ ProductCategory: 'Electronics', 'Clothing', 'Electronics', 'Furniture', 'Clothing','Electronics', 'Furniture', 'Clothing', 'Furniture', 'Electronics'

➢ Region: 'North', 'South', 'North', 'East', 'West', 'North', 'East', 'West', 'South','North'

➢ Amount: 200, 150, 300, 450, 200, 250, 300, 180, 350, 400

In [20]:
import pandas as pd

transactions = pd.DataFrame({
    'TransactionID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],

    'ProductCategory': [
        'Electronics', 'Clothing', 'Electronics', 'Furniture', 'Clothing',
        'Electronics', 'Furniture', 'Clothing', 'Furniture', 'Electronics'
    ],

    'Region': [
        'North', 'South', 'North', 'East', 'West',
        'North', 'East', 'West', 'South', 'North'
    ],

    'Amount': [200, 150, 300, 450, 200, 250, 300, 180, 350, 400]
})

print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400


# 2. Data Exploration:
● Display the transactions DataFrame and its basic information, including head, tail,
shape, column names, and data types.

● Display only the 'ProductCategory' and 'Amount' columns.

● Retrieve the last 3 columns of the DataFrame using iloc or loc.

● Filter rows where the 'Region' is 'North' and 'Amount' is greater than 200.

● Find the value counts for the 'ProductCategory' column.

● Find the unique values in the 'Region' column.

● Group by 'Region' and find the mean amount for each region.

In [21]:
# DataFrame display

print(transactions)

# First 5 rows – head()

print(transactions.head())

# Last 5 rows – tail()

print(transactions.tail())

# Shape

print(transactions.shape)

# Column names

print(transactions.columns)

#Data types

print(transactions.dtypes)

# Total basic information

transactions.info()

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400
   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
   TransactionID ProductCategory Region  Amount
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West 

In [22]:
# Display only the 'ProductCategory' and 'Amount' columns.

print(transactions[['ProductCategory', 'Amount']])

  ProductCategory  Amount
0     Electronics     200
1        Clothing     150
2     Electronics     300
3       Furniture     450
4        Clothing     200
5     Electronics     250
6       Furniture     300
7        Clothing     180
8       Furniture     350
9     Electronics     400


In [23]:
# Retrieve the last 3 columns of the DataFrame using iloc or loc.

print(transactions.iloc[:, -3:])

  ProductCategory Region  Amount
0     Electronics  North     200
1        Clothing  South     150
2     Electronics  North     300
3       Furniture   East     450
4        Clothing   West     200
5     Electronics  North     250
6       Furniture   East     300
7        Clothing   West     180
8       Furniture  South     350
9     Electronics  North     400


In [24]:
# Filter rows where the 'Region' is 'North' and 'Amount' is greater than 200.

result = transactions[
    (transactions['Region'] == 'North') &
    (transactions['Amount'] > 200)
]

print(result)

   TransactionID ProductCategory Region  Amount
2            103     Electronics  North     300
5            106     Electronics  North     250
9            110     Electronics  North     400


In [25]:
# Find the value counts for the 'ProductCategory' column.

print(transactions['ProductCategory'].value_counts())

ProductCategory
Electronics    4
Clothing       3
Furniture      3
Name: count, dtype: int64


In [26]:
# Find the unique values in the 'Region' column.

print(transactions['Region'].unique())

# nunique

print(transactions['Region'].nunique())

['North' 'South' 'East' 'West']
4


In [27]:
# Group by 'Region' and find the mean amount for each region.

mean_amount = transactions.groupby('Region')['Amount'].mean()

print(mean_amount)

Region
East     375.0
North    287.5
South    250.0
West     190.0
Name: Amount, dtype: float64


# 3. Manipulating the DataFrame:

● Modify the 'Amount' for the transaction with TransactionID 102 to 165.

● Add a new column 'Discount' by calculating 10% of the 'Amount'.

● Remove the row with TransactionID 109.

● Delete the 'Discount' column from the DataFrame.

In [28]:
# Modify the 'Amount' for the transaction with TransactionID 102 to 165.

transactions.loc[transactions['TransactionID'] == 102, 'Amount'] = 165

print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400


In [29]:
# Add a new column 'Discount' by calculating 10% of the 'Amount'.

transactions['Discount'] = transactions['Amount'] * 0.10

print(transactions)

   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
8            109       Furniture  South     350      35.0
9            110     Electronics  North     400      40.0


In [30]:
# Remove the row with TransactionID 109.

transactions = transactions[transactions['TransactionID'] != 109]

print(transactions)

   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
9            110     Electronics  North     400      40.0


In [31]:
# Delete the 'Discount' column from the DataFrame.

transactions = transactions.drop('Discount', axis=1)

print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
9            110     Electronics  North     400


# Thank you